---
title: "Product review: Google Analytics"
author: "Impact team"
date: "`r Sys.Date()`"
output: 
    flexdashboard::flex_dashboard:
        source_code: embed
        vertical_layout: scroll
        orientation: rows
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(fuzzyjoin)
library(DT)
# library(kableExtra)
# library(zoo)
library(plotly)
library(reactable)
```

```{r, include = FALSE}
# Specify time period GA data is available for
month_start <- ym("2019-06")
month_end <- ym("2022-06")
```


```{r, include = FALSE}
# Calculate number of months
months_diff <- floor((month_start %--% month_end) / dmonths(1))

# Create vector with all the relevant months
month_list <- month_start + months(0:months_diff)

# Generate file names using months specified above
downloads_filename <- map(month_list, ~ sprintf("./download_analytics/HSC dashboard - Engagement and implementation_All webpages_ links and downloads_Table_%s.csv", as.character(.x) %>% str_remove("-01$")))

views_filename <- map(month_list, ~ sprintf("./download_analytics/HSC dashboard - Engagement and implementation_All webpages_ links and downloads_Table_views_%s.csv", as.character(.x) %>% str_remove("-01$")))
```


```{r, include = FALSE}
# Import data
import_data <- function(filenames, col_string) {
    filenames %>%
        set_names() %>%
        map_dfr(read_csv, col_types = col_string, .id = "filename")
}


downloads_data <- import_data(downloads_filename, "ccd")

views_data <- import_data(views_filename, "cd")

```


```{r, include = FALSE}
# Extract the date from the file name
extract_date <- function(table, date_regex) {
    table %>% 
        mutate(year_month = str_extract(filename, date_regex) %>% ym(.)) %>% 
        select(-filename) %>%
        janitor::clean_names() %>%
        select(year_month, everything())
}

downloads_data <- extract_date(downloads_data, "(?<=Table_)\\d{4}-\\d{2}(?=.csv)")

views_data <- extract_date(views_data, "(?<=Table_views_)\\d{4}-\\d{2}(?=.csv)")

```

```{r, include = FALSE}
# List of products with filename regex
dl_product_list <- list("QSSIT" = "((QS)|(quality-standard))-service-improvement-template",
                      "Baseline assessment tool" = "baseline-assessment-tool",
                      "Resource planner" = "resource-planner",
                     "Resource impact template" = "resource-impact-template",
                     "Resource impact report" = "resource-impact-report"
)

views_product_list <- list("Resource impact report" = "resource-impact-report",
                           "Resource impact statement" = "resource-impact-statement",
                           "Resources for local partnerships" = "(stpsupport.nice.org.uk)|(indepth.nice.org.uk/respiratory)"
)

```

Downloads
=====================================

Inputs {.sidebar}
-------------------------------------

```{r, echo = FALSE}
selectInput("dl_select_products", 
                "Select products to view downloads data:",
                choices = dl_product_list,
                multiple = TRUE)
```

Note, while the QSSIT and resource planner are the same product regardless of which webpage it exists on, the BATs, resource impact templates and resource impact reports are specific to the guideline they belong to.

When thinking about resource use, note that while there may be considerable downloads of e.g. the resource impact reports when the downloads across all the reports are combined, each individual report may only be getting a handful of downloads monthly, despite requiring a lot of resource to produce, as they are guideline/topic-specific.

```{r, echo = FALSE}
dl_selected <- reactive({
    dl_selected <- downloads_data %>% 
            filter(str_detect(file, regex(str_c(input$dl_select_products, collapse = "|"), ignore_case = TRUE)))
    
    dl_product_list_tbl <- tibble(product = names(dl_product_list), regex = dl_product_list)

    dl_selected %>% 
        regex_inner_join(dl_product_list_tbl,
                         by = c(file = "regex")) %>% 
        select(-regex) %>% 
        mutate(product = as_factor(product))
    })

dl_monthly <- reactive({
    dl_selected() %>% 
        group_by(product, year_month) %>% 
        summarise(monthly_downloads = sum(downloads))
})
```

Row {.tabset .tabset-fade}
-------------------------------------

### How much are the products being downloaded across all NICE webpages, monthly?

```{r, echo = FALSE}
renderPlotly({
    req(input$dl_select_products)
    
    fig <- ggplot(data = dl_monthly(),
                  aes(x = year_month, y = monthly_downloads, colour = product)) +
        geom_line() +
        labs(x = "Month",
             y = "Downloads") +
        scale_y_continuous(expand = c(0,0),
                           limits = c(0, NA)) +
        scale_x_date(date_breaks = "6 months",
                     date_labels = "%b %Y")


    ggplotly(fig)
})
```

### Table

```{r, echo = FALSE}
renderDT(dl_monthly(),
         filter = "top",
         extensions = c("Scroller", "Buttons"),
         options = list(
             scrollY = 400,
             scrollX = TRUE,
             scroller = TRUE,
             dom = "Bfrtip",
             buttons = c('copy', 'csv', 'excel')
             ),
         rownames = FALSE) 
```

Row {.tabset .tabset-fade}
-------------------------------------

### Which pages are the products most frequently downloaded from?

```{r, include = FALSE}
download_page <- reactive({
    dl_selected() %>%
        group_by(product) %>% 
        mutate(downloaded_from = fct_lump_prop(page_path, w = downloads, prop = 0.05)) %>% 
        ungroup()
})
```


```{r, echo = FALSE}
renderPlotly({
    req(input$dl_select_products)
    
    highlight_line <- highlight_key(dl_selected(), ~page_path)
    
    page_line <- highlight_line %>%
        ggplot(aes(x = year_month,
                   y = downloads,
                   group = page_path,
                   colour = product)) +
        geom_line() +
        labs(x = "Month",
             y = "Downloads") +
        scale_y_continuous(expand = c(0,0),
                           limits = c(0, NA)) +
        scale_x_date(date_breaks = "6 months",
                     date_labels = "%b %Y")


    ggplotly(page_line, tool_tip = "page_path") %>% 
        highlight(on = "plotly_hover",
                  off = "plotly_doubleclick",
                  color = "red")
})
```

### Top pages

All pages contributing less than 5% to the monthly download of a product are collapsed into "Other".

```{r, echo = FALSE}
renderPlotly({
    req(input$dl_select_products)
    
    source_fig <- download_page() %>%
        group_by(product, year_month, downloaded_from) %>%
        summarise(monthly_downloads = sum(downloads)) %>%
        ggplot(aes(x = year_month,
                   y = monthly_downloads, 
                   colour = product, 
                   linetype = downloaded_from)) +
        geom_line() +
        labs(x = "Month",
             y = "Downloads") +
        scale_y_continuous(expand = c(0,0),
                           limits = c(0, NA)) +
        scale_x_date(date_breaks = "6 months",
                     date_labels = "%b %Y")


    ggplotly(source_fig)
})

```

### Table
```{r, echo = FALSE}
renderReactable({
    download_page() %>%
        select(-file) %>% 
        reactable(.,
                  filterable = TRUE,
                  searchable = TRUE,
                  groupBy = c("product", "year_month", "downloaded_from"),
                  columns = list(
                      downloads = colDef(aggregate = "sum")
                      )
                  )
})

```

### Average monthly downloads per page
Relevant for the baseline assessment tool, resource impact template and resource impact report only.

```{r, include = FALSE}
average_download <- reactive({
    dl_selected() %>%
        group_by(product, year_month) %>% 
        summarise(average_monthly_downloads = mean(downloads) %>% round(1)) %>% 
        filter(product %in% c("Baseline assessment tool", 
                              "Resource impact template", 
                              "Resource impact report"))
})
```


```{r, echo = FALSE}
renderPlotly({
    req(input$dl_select_products)
    
    average_fig <- average_download() %>%
        ggplot(aes(x = year_month,
                   y = average_monthly_downloads, 
                   colour = product)) +
        geom_line() +
        labs(x = "Month",
             y = "Average downloads") +
        scale_y_continuous(expand = c(0,0),
                           limits = c(0, NA)) +
        scale_x_date(date_breaks = "6 months",
                     date_labels = "%b %Y")


    ggplotly(average_fig)
})

```

### Table (for averages)
```{r, echo = FALSE}
renderDT(average_download(),
         filter = "top",
         extensions = c("Scroller", "Buttons"),
         options = list(
             scrollY = 400,
             scrollX = TRUE,
             scroller = TRUE,
             dom = "Bfrtip",
             buttons = c('copy', 'csv', 'excel')
             ),
         rownames = FALSE) 
```



Row
-------------------------------------

### Raw downloads data showing page downloaded from and file download URL

```{r, echo = FALSE}
renderDT(dl_selected() %>% select(product, everything()),
         filter = "top",
         extensions = c("Scroller", "Buttons"),
         options = list(
             scrollY = 400,
             scrollX = TRUE,
             scroller = TRUE,
             dom = "Bfrtip",
             buttons = c('copy', 'csv', 'excel')
             ),
         rownames = FALSE) 
```

Views
=====================================

Inputs {.sidebar}
-------------------------------------

```{r, echo = FALSE}
selectInput("views_select_products", 
                "Select products to view page views for:",
                choices = views_product_list,
                multiple = TRUE)
```


```{r, echo = FALSE}
views_selected <- reactive({
    views_selected <- views_data %>% 
            filter(str_detect(page_path, regex(str_c(input$views_select_products, collapse = "|"), ignore_case = TRUE)))
    
    views_product_list_tbl <- tibble(product = names(views_product_list), regex = views_product_list)

    views_selected %>% 
        regex_inner_join(views_product_list_tbl,
                         by = c(page_path = "regex")) %>% 
        select(-regex) %>% 
        mutate(product = as_factor(product))
    })

views_monthly <- reactive({
    views_selected() %>% 
        group_by(product, year_month) %>% 
        summarise(monthly_views = sum(views))
})
```

Row {.tabset .tabset-fade}
-------------------------------------

### How much are the products being viewed across all NICE webpages, monthly?

```{r, echo = FALSE}
renderPlotly({
    req(input$views_select_products)
    
    monthly_views_fig <- ggplot(data = views_monthly(),
                  aes(x = year_month, y = monthly_views, colour = product)) +
        geom_line() +
        labs(x = "Month",
             y = "Views") +
        scale_y_continuous(expand = c(0,0),
                           limits = c(0, NA)) +
        scale_x_date(date_breaks = "6 months",
                     date_labels = "%b %Y")


    ggplotly(monthly_views_fig)
})
```

### Table

```{r, echo = FALSE}
renderDT(views_monthly(),
         filter = "top",
         extensions = c("Scroller", "Buttons"),
         options = list(
             scrollY = 400,
             scrollX = TRUE,
             scroller = TRUE,
             dom = "Bfrtip",
             buttons = c('copy', 'csv', 'excel')
             ),
         rownames = FALSE) 
```

Row {.tabset .tabset-fade}
-------------------------------------

### How often is each individual page viewed?

```{r, echo = FALSE}
renderPlotly({
    req(input$views_select_products)
    
    views_highlight_line <- highlight_key(views_selected(), ~page_path)
    
    views_page_line <- views_highlight_line %>%
        ggplot(aes(x = year_month,
                   y = views,
                   group = page_path,
                   colour = product)) +
        geom_line() +
        labs(x = "Month",
             y = "Views") +
        scale_y_continuous(expand = c(0,0),
                           limits = c(0, NA)) +
        scale_x_date(date_breaks = "6 months",
                     date_labels = "%b %Y")


    ggplotly(views_page_line, tool_tip = "page_path") %>% 
        highlight(on = "plotly_hover",
                  off = "plotly_doubleclick",
                  color = "red")
})
```

### Table
```{r, echo = FALSE}
renderReactable({
    views_selected() %>%
        reactable(.,
                  filterable = TRUE,
                  searchable = TRUE,
                  groupBy = c("product", "year_month"),
                  columns = list(
                      views = colDef(aggregate = "sum")
                      )
                  )
})

```

### Average monthly views per page

```{r, include = FALSE}
average_views <- reactive({
    views_selected() %>%
        group_by(product, year_month) %>% 
        summarise(average_monthly_views = mean(views) %>% round(1))
})
```


```{r, echo = FALSE}
renderPlotly({
    req(input$views_select_products)
    
    average_views_fig <- average_views() %>%
        ggplot(aes(x = year_month,
                   y = average_monthly_views, 
                   colour = product)) +
        geom_line() +
        labs(x = "Month",
             y = "Average views") +
        scale_y_continuous(expand = c(0,0),
                           limits = c(0, NA)) +
        scale_x_date(date_breaks = "6 months",
                     date_labels = "%b %Y")


    ggplotly(average_views_fig)
})

```

### Table (for averages)
```{r, echo = FALSE}
renderDT(average_views(),
         filter = "top",
         extensions = c("Scroller", "Buttons"),
         options = list(
             scrollY = 400,
             scrollX = TRUE,
             scroller = TRUE,
             dom = "Bfrtip",
             buttons = c('copy', 'csv', 'excel')
             ),
         rownames = FALSE) 
```

Row
-------------------------------------

### Raw views data

```{r, echo = FALSE}
renderDT(views_selected() %>% select(product, everything()),
         filter = "top",
         extensions = c("Scroller", "Buttons"),
         options = list(
             scrollY = 400,
             scrollX = TRUE,
             scroller = TRUE,
             dom = "Bfrtip",
             buttons = c('copy', 'csv', 'excel')
             ),
         rownames = FALSE) 
```
