---
title: "Preprocessing"
author: "Impact team"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)

```


```{r, include = FALSE}
# Specify time period GA data is available for
month_start <- ym("2019-06")
month_end <- ym("2022-06")
```


```{r, include = FALSE}
# Calculate number of months
months_diff <- floor((month_start %--% month_end) / dmonths(1))

# Create vector with all the relevant months
month_list <- month_start + months(0:months_diff)

# Generate file names using months specified above
downloads_filename <- map(month_list, ~ sprintf("./download_analytics/HSC dashboard - Engagement and implementation_All webpages_ links and downloads_Table_%s.csv", as.character(.x) %>% str_remove("-01$")))

views_filename <- map(month_list, ~ sprintf("./download_analytics/HSC dashboard - Engagement and implementation_All webpages_ links and downloads_Table_views_%s.csv", as.character(.x) %>% str_remove("-01$")))
```


```{r, include = FALSE}
# Import data
import_data <- function(filenames, col_string) {
    filenames %>%
        set_names() %>%
        map_dfr(read_csv, col_types = col_string, .id = "filename")
}


downloads_data <- import_data(downloads_filename, "ccd")

views_data <- import_data(views_filename, "cd")

```


```{r, include = FALSE}
# Extract the date from the file name
extract_date <- function(table, date_regex) {
    table %>% 
        mutate(year_month = str_extract(filename, date_regex) %>% ym(.)) %>% 
        select(-filename) %>%
        janitor::clean_names() %>%
        select(year_month, everything())
}

downloads_data <- extract_date(downloads_data, "(?<=Table_)\\d{4}-\\d{2}(?=.csv)")

views_data <- extract_date(views_data, "(?<=Table_views_)\\d{4}-\\d{2}(?=.csv)")

```

```{r, include = FALSE}
# List of products with filename regex
dl_product_list <- list("QSSIT" = "((QS)|(quality-standard))-service-improvement-template",
                      "Baseline assessment tool" = "baseline-assessment-tool",
                      "Resource planner" = "resource-planner",
                     "Resource impact template" = "resource-impact-template",
                     "Resource impact report" = "resource-impact-report"
)

views_product_list <- list("Resource impact report" = "resource-impact-report",
                           "Resource impact statement" = "resource-impact-statement",
                           "Resources for local partnerships" = "(stpsupport.nice.org.uk)|(indepth.nice.org.uk/respiratory)"
)

```

```{r}
# Filter for relevant products and save
downloads_data %>% 
    filter(str_detect(file, 
                      regex(str_c(dl_product_list, collapse = "|"), 
                            ignore_case = TRUE))) %>% 
    write_csv('./output/downloads_data.csv')

views_data %>% 
    filter(str_detect(page_path, 
                      regex(str_c(views_product_list, collapse = "|"), 
                            ignore_case = TRUE))) %>% 
    write_csv('./output/views_data.csv')
```

